//go:build !lib

// Source mode: compile C sources directly with CGO.
// Usage: go build (default)
// Requires: CGO_CFLAGS_ALLOW="-mavx.*|-msse.*|-mfma|-mavx512.*"
// Generated by CMake - DO NOT EDIT MANUALLY
package ds

/*
#cgo CFLAGS: -I${SRCDIR}/include
#cgo CFLAGS: -I${SRCDIR}/ds-c
#cgo CFLAGS: -I${SRCDIR}/modules/platform/include
#cgo CFLAGS: -I${SRCDIR}/third_party/xxhash
#cgo CFLAGS: -mavx2 -mfma -O2 -Wall -std=c11
#cgo darwin CFLAGS: -D_DARWIN_C_SOURCE
#cgo linux CFLAGS: -D_POSIX_C_SOURCE=200112L
#cgo LDFLAGS: -lm -latomic

#cgo linux LDFLAGS: ${SRCDIR}/modules/platform/build/linux_amd64/libfinkit_platform_static.a -lm -lgcov
#cgo darwin,arm64 LDFLAGS: ${SRCDIR}/modules/platform/build/darwin_arm64/libfinkit_platform_static.a -lm -lgcov
#cgo darwin,amd64 LDFLAGS: ${SRCDIR}/modules/platform/build/darwin_x86_64/libfinkit_platform_static.a -lm -lgcov
#cgo windows LDFLAGS: ${SRCDIR}/modules/platform/build/windows_amd64/libfinkit_platform_static.a -lm -lgcov

#include "bloom_filter.h"
#include "roaring_bitmap.h"
#include "ring_buffer.h"
#include "generic_ring_buffer.h"
#include "mem_pool.h"
#include "arena.h"
#include "priority_queue.h"


// DS sources
#include "bloom_filter.c"
#include "roaring_bitmap.c"
#include "ring_buffer.c"
#include "generic_ring_buffer.c"
#include "mem_pool.c"
#include "arena.c"
#include "priority_queue.c"
*/
import "C"
