//go:build !lib

// Source mode: compile C sources directly with CGO.
// Usage: go build (default)
// Requires: CGO_CFLAGS_ALLOW="-mavx.*|-msse.*|-mfma|-mavx512.*"
// Generated by CMake - DO NOT EDIT MANUALLY
package ds

/*
#cgo CFLAGS: -I${SRCDIR}/include
#cgo CFLAGS: -I${SRCDIR}/ds-c
#cgo CFLAGS: -I${SRCDIR}/modules/platform/include
#cgo CFLAGS: -I${SRCDIR}/third_party/xxhash
#cgo CFLAGS: -mavx2 -mfma -O2 -Wall -std=c11
#cgo darwin CFLAGS: -D_DARWIN_C_SOURCE
#cgo linux CFLAGS: -D_POSIX_C_SOURCE=200112L
#cgo LDFLAGS: -lm -latomic

#include "bloom_filter.h"
#include "roaring_bitmap.h"
#include "ring_buffer.h"
#include "generic_ring_buffer.h"
#include "mem_pool.h"
#include "arena.h"

// Platform sources
#include "modules/platform/src/simd_detect.c"
#include "modules/platform/src/mem_aligned.c"

// DS sources
#include "bloom_filter.c"
#include "roaring_bitmap.c"
#include "ring_buffer.c"
#include "generic_ring_buffer.c"
#include "mem_pool.c"
#include "arena.c"
*/
import "C"
